# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, distributive, fileEmbed, filepath, GLFWB, GLUtil, linear
, OpenGL, OpenGLRaw, vector, vinyl, vinylGl
}:

cabal.mkDerivation (self: {
  pname = "haskell-OpenGL-examples";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [
    distributive fileEmbed filepath GLFWB GLUtil linear OpenGL
    OpenGLRaw vector vinyl vinylGl
  ];
  meta = {
    homepage = "http://github.com/bergey/haskell-OpenGL-examples";
    description = "Comparative examples of OpenGL in Haskell";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
